image: node:8.10.0

cache:
  paths:
  - node_modules/

before_script:
   #generate ssh key
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
     - mkdir -p ~/.ssh
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
     - chmod 600 ~/.ssh/id_rsa
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
     - npm install
     - npm install lint
     
  
stages:
     - build
     - test
     - deploy

install_dependencies:
      stage: build
      script:
        - npm install
      artifacts:
        paths:
          - node_modules/

            #test_async:
            #stage: test
            #script:
            #- npm test

# Running Lint
#lint:
#  stage: test
#  script:
#    - npm run lint

# Running test
test:
  stage: test
  script:
    - npm run test

deployToAWS:
  only:
    - ST-90
  stage: deploy
  script:
    - bash deploy/deploy.sh

