# Node docker image on which this would be run
image: node:8.9.0


#This command is run before actual stages start running

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - npm install

stages:
  - deploy

deployToAWS:
  stage: deploy
  only:
    - schedules
  script:
    - bash deploy/deploy.sh
